global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: admin
    metrics_path: /probe
    params:
      module:
        - http_default
    static_configs:
      - targets:
          - https://google.com
          - https://domain.tld
          - https://domain.tldd
        labels:
          username: admin
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: test
    metrics_path: /probe
    params:
      module:
        - http_default
    static_configs:
      - targets: []
        labels:
          username: test
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: rakib4kbd
    metrics_path: /probe
    params:
      module:
        - http_default
    static_configs:
      - targets:
          - https://domain.tld
        labels:
          username: rakib4kbd
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
rule_files:
  - alert_rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
